### ISSUE TITLE
Fix labels override logic

### ISSUE THREAD

**Issue by remorhaz** [allure-framework/allure-php-commons2#34]
As for now, labels from lower levels (i.e. from test method) just append to the list that starts to form at higher levels (i.e. test class). In fact, this behavior doesn't allow to override labels.

There are several ways of solving this problem:

1. Revert the list of labels, so that last-formed label is placed on top of label list. Allure will use the first one from list automatically.
2. Build map of labels by name and overwrite label with same name, if it exists. This will forbid having several labels with same name. Probably this is the right behavior.

**Comment by baev** [comment]
maybe we should make it so Allure uses latest found label instead? Kinda breaking change, but makes much more sense

**Comment by remorhaz** [comment]
BC indeed, but sounds reasonable.

By the way, option 2 seems to break existing behavior: [here](https://docs.qameta.io/allure-testops/faq/labels/#how-it-works) we can see example of several `tag` labels in same test.
